config/routes.rb
AsareoCom::Application.routes.draw do
 
  get "texts/edit"
  resources :texts do
    collection do
      get 'render_fields/:order_id', to: 'texts#render_fields'
      get 'stories', to: 'texts#stories'
      get 'search', to: 'texts#search'
    end
    member do
      get 'quit', to: 'texts#quit'
      post "set_timer", to: "application#set_text_correct_timer"
      post "unlock_text", to: "application#unlock_text"
    end
  end

  resources :projects #do
    devise_for :users, :controllers => {:registrations => "users/registrations"}
    namespace :users do
      get 'password/change', to: "passwords#edit"
      put 'password/update', to: "passwords#update"
  end

  resources :orders,  only: [:index, :show] do
    collection do
      get 'reserved', to:"orders#reserved"
      get 'optional', to:"orders#optional"
      get 'cdc/:cdc_id', to:"orders#show"
    end
    put 'create/:reserver_id', to:"orders#create", as: "create"
    put 'delete/:id_reserve', to:"orders#delete", as: "delete"
  end

  namespace :cp do
    root 'texts#index'

    devise_for :salaries, :controllers => { :registrations => "cp/salaries/registrations", :sessions => "cp/salaries/sessions", :passwords => "cp/salaries/passwords"}

    resources :texts, :only => [:index, :edit, :update] do
      member do
        get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end

    resources :reviewers, :only => [:index, :new, :create, :edit, :update, :destroy]
    get 'reviewers', to: "reviewers#index"

    resource :projects, :only => [:index, :new, :create]
    resources :clients, :only => [:index, :new, :create, :edit, :update] do
      member do
        delete "disable", to: "clients#disable"
        put "enable", to: "clients#enable"
      end
      resources :cdcs, :only => [:index, :new, :create, :edit, :update, :destroy] do
        resources :orders, :only => [:create, :new]
      end 
      resources :orders, :only => [:new]
    end

    resources :orders, :only => [:new, :create, :index, :edit, :update, :destroy, :show] do
      collection do
        get 'stories', to: 'orders#stories'
        get ':id/texts/', to: "orders#showTexts"
      end
    end

    resources :categories_users, :only => [:index, :create]
    resources :levels_users, :only => [:index, :create]

    get "texts/:id/:status", to: "texts#show", as: 'text_show'
    get 'client/:client_id', to:"orders#show"
    get 'cdc/:cdc_id', to:"orders#show"
    get 'orders/new/:id', to: "orders#new", as: 'orderuser'
    get 'levels_users/:id', to: "levels_users#manage",  as: 'level'
    get 'level_user/manage', to: "levels_users#manage",  as: 'managelist'
    get 'password/edit', to: "passwords#edit"
    get 'projects', to: "projects#index" 
    put 'password/update', to: "passwords#update"

  end

  namespace :reviewer do
    root 'texts#index'
    devise_for :salaries, :controllers => { :registrations => "reviewer/salaries/registrations", :sessions => "reviewer/salaries/sessions", :passwords => "reviewer/salaries/passwords", :confirmations => "reviewer/salaries/confirmations"}
    resources :texts, :only => [:index, :edit, :update] do
     member do
       get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end
    

    get 'password/edit', to: "passwords#edit"
    put 'password/update', to: "passwords#update"
    
  end

  namespace :administration do
    devise_for :admins, :controllers => { :sessions => "administration/admins/sessions", :passwords => "administration/admins/passwords"}
    
    resources :texts, :only => [:index, :edit, :update] do
      member do
        get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end

    resources :managers, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :users, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :reviewers, :only => [:index, :new, :create, :edit, :update, :destroy]

    get 'password/edit', to: "passwords#edit"
    put 'password/update', to: "passwords#update"

    resources :projects, :only => [:index, :new, :create, :edit, :update, :destroy]    

    root 'texts#index'
  end

  root 'home#index'

end

app/views/shared/_footer.html.erb
<p>© 2013 Maïka-Rédaction</p>

app/views/shared/_nav_admin.html.erb
<div class="accordion" id="leftMenu"> 
  <div class="accordion-group no_margin_bottom">
    <div class="accordion-heading"><%= link_to "Accueil", administration_root_path, :class =>"accordion-toggle" %>
    </div>
  </div>
  <% if current_administration_admin.nil? %>
    <div class="accordion-group no_margin_bottom">
      <div class="accordion-heading"><%= link_to "Se connecter", new_administration_admin_session_path, :class =>"accordion-toggle" %>
      </div>
    </div>
  <% else %>
    <div class="accordion-group no_margin_bottom">
      <div class="accordion-heading"><%= link_to "Modifier le mot de passe", administration_password_edit_path, :class =>"accordion-toggle" %>
      </div>
    </div>
    <div class="accordion-group no_margin_bottom">
     <div class="#leftMenu accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#leftMenu" href="#collapseOne">
            <!--i class="icon-th-list"></i--> Gerer  
          </a>
     </div>
      <div id="collapseOne" class="accordion-body collapse" 
        <% if @active_menu == "clients" %>
          style="height: auto;"
        <% else %>
          style="height: 0;"
        <% end %>
      >
        <div class="accordion-inner nav_style">                  
          <ul class="nav2">
            <li><%= link_to " Chef de projet", administration_managers_url, :class =>"link_nav2" %></li>
            <li><%= link_to "Correcteurs", administration_reviewers_url, :class =>"link_nav2" %></li>
            <li><%= link_to "Freelance", administration_users_url, :class =>"link_nav2" %></li>
            <li><%= link_to "Commandes à supprimer", administration_orders_path, :class =>"link_nav2" %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="accordion-group no_margin_bottom">
      <div class="accordion-heading"><%= link_to "Deconnecter", destroy_administration_admin_session_path, :method => :delete, :class =>"accordion-toggle" %>
      </div>
    </div>
  <%end%>
</div>

app/views/shared/_nav_cp.html.erb
<div class="accordion" id="leftMenu"> 
  <div class="accordion-group no_margin_bottom"><div class="accordion-heading"><%= link_to "Accueil", cp_root_path, :class =>"accordion-toggle" %></div></div>
  <% if current_cp_salary.nil? %>
    <div class="accordion-group no_margin_bottom">
      <div class="accordion-heading"><%= link_to "Se connecter", new_cp_salary_session_path, :class =>"accordion-toggle"%>
      </div>
    </div>
  <% else %> 
    <div class="accordion-group no_margin_bottom">
         <div class="#leftMenu accordion-heading">              
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#leftMenu" href="#collapseOne">
                <!--i class="icon-th-list"></i--> Mes commandes
              </a>
         </div>
          <div id="collapseOne" class="accordion-body collapse" 
            <% if @active_menu == "orders" %>
              style="height: auto;"
            <% else %>
              style="height: 0;"
            <% end %>
          >
              <div class="accordion-inner nav_style">                  
                <ul class="nav2">
                    <li><%= link_to " Créer", new_cp_order_path, :class =>"link_nav2" %></li>
                    <li><%= link_to "Mes commandes en cours ", cp_orders_path, :class =>"link_nav2" %></li>
                    <li><%= link_to "Mes textes", cp_texts_path,:class =>"link_nav2" %></li>
                    <li><%= link_to "Historique de mes commandes", stories_cp_orders_path, :class =>"link_nav2" %></li>
                </ul>
            </div>
        </div>
      </div>


      <div class="accordion-group no_margin_bottom">
         <div class="#leftMenu accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#leftMenu" href="#collapseTwo">
                <!--i class="icon-th-list"></i--> Mes clients  
              </a>
         </div>
          <div id="collapseTwo" class="accordion-body collapse" 
            <% if @active_menu == "clients" %>
              style="height: auto;"
            <% else %>
              style="height: 0;"
            <% end %>
          >
              <div class="accordion-inner nav_style">                  
                <ul class="nav2">
                    <li><%= link_to " Ajouter un nouveau clients", new_cp_client_path, :class =>"link_nav2" %></li>
                    <li><%= link_to "Liste des clients ", cp_clients_path, :class =>"link_nav2" %></li>
                </ul>
            </div>
        </div>
      </div>


      <div class="accordion-group no_margin_bottom">
         <div class="#leftMenu accordion-heading">              
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#leftMenu" href="#collapseThree">
                <!--i class="icon-th-list"></i--> Mes rédacteurs
              </a>
         </div>
          <div id="collapseThree" class="accordion-body collapse" 
            <% if @active_menu == "fls" %>
              style="height: auto;"
            <% else %>
              style="height: 0;"
            <% end %>
          >
              <div class="accordion-inner nav_style">                  
                <ul class="nav2">
                    <li><%= link_to " Nouveau FL", "#", :class =>"link_nav2" %></li>
                    <li><%= link_to "  Liste des FL", cp_levels_users_path, :class =>"link_nav2" %></li>
                    <li><%= link_to "Gestion niveaux FL", cp_managelist_path, :class =>"link_nav2" %></li>
                </ul>
            </div>
        </div>
      </div>


      <div class="accordion-group no_margin_bottom">
         <div class="#leftMenu accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#leftMenu" href="#collapseFour">
                <!--i class="icon-th-list"></i--> Mes correcteurs
              </a>
         </div>
          <div id="collapseFour" class="accordion-body collapse" style="height: 0px; ">
              <div class="accordion-inner nav_style">                  
                <ul class="nav2">
                    <li><%= link_to "Nouveau correcteur", new_cp_reviewer_url, :class =>"link_nav2" %></li>
                    <li><%= link_to "Liste des correcteurs", cp_reviewers_url, :class =>"link_nav2" %></li>
                </ul>
            </div>
        </div>
      </div>


      <div class="accordion-group no_margin_bottom">
         <div class="#leftMenu accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#leftMenu" href="#collapseFive">
                                <!--i class="icon-th-list"></i--> Mon compte
              </a>
         </div>
          <div id="collapseFive" class="accordion-body collapse" style="height: 0px; ">
              <div class="accordion-inner nav_style">                  
                <ul class="nav2">
                    <li><%= link_to "Modifier mot de passe", cp_password_edit_path, :class =>"link_nav2" %></li>
                    <li><%= link_to "Désactiver", cp_salary_registration_path, :method => :delete, :class =>"link_nav2", data: { confirm: 'Etes-vous sur de vouloir désactiver votre compte ?' }%></li>
                    <li><%= link_to "Deconnecter",destroy_cp_salary_session_path, :method => :delete, :class =>"link_nav2" %></li>
                </ul>
            </div>
        </div>
      </div>

      <div class="accordion-group no_margin_bottom">
        <div class="accordion-heading"><%= link_to "Historique", stories_cp_texts_path, :class =>"accordion-toggle" %>
        </div>
      </div>

  <% end %>
</div>

app/views/shared/_nav_front.html.erb
<div class="accordion" id="leftMenu"> 
  <!--li><%= link_to "Accueil", root_path %></li-->
  <% if current_user.nil? %>

    <div class="accordion-group no_margin_bottom">
      <div class="accordion-heading"><%= link_to "Se connecter", new_user_session_path, :class =>"accordion-toggle" %>
      </div>
    </div>

    <div class="accordion-group no_margin_bottom">
      <div class="accordion-heading"><%= link_to "Créer un compte", new_user_registration_path, :class =>"accordion-toggle" %>
      </div>
    </div>
    <!--li><%= link_to "Se connecter", new_user_session_path %></li>
    <li><%= link_to "Créer un compte", new_user_registration_path %></li-->
  <% else %>
    <div class="accordion-group no_margin_bottom">
      <div class="accordion-heading"><%= link_to "Accueil", root_path, :class =>"accordion-toggle" %></div>

   </div>

    <div class="accordion-group no_margin_bottom">
      <div class="#leftMenu accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#leftMenu" href="#collapseTwo">
                                <!--i class="icon-th-list"></i--> Mon compte
              </a>
      </div>
        <div id="collapseTwo" class="accordion-body collapse" style="height: 0px; ">
            <div class="accordion-inner nav_style">                  
                <ul class="nav2">
                    <li><%= link_to "Modifier les informations", edit_user_registration_path, :class =>"link_nav2" %></li>
                    <li><%= link_to "Désactiver mon compte",user_registration_path, :method => :delete, data: { confirm: 'Etes-vous sur de vouloir désactiver votre compte ?' }, :class =>"link_nav2"%></li>
                    <li><%= link_to "Deconnecter",destroy_user_session_path, :method => :delete, :class =>"link_nav2" %></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="accordion-group no_margin_bottom">
      <div class="#leftMenu accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#leftMenu" href="#collapseThree">
                    Commandes
              </a>
      </div>
        <div id="collapseThree" class="accordion-body collapse" style="height: 0px; ">
            <div class="accordion-inner nav_style">                  
                <ul class="nav2">
                    <li><%= link_to "Commande(s) à réserver", orders_path, :class =>"link_nav2" %></li>
                    <li><%= link_to "Mes textes à rédiger",new_text_path, :class =>"link_nav2"%></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="accordion-group no_margin_bottom">
       <div class="#leftMenu accordion-heading">
           <%= link_to "Historique", texts_url,:class =>"accordion-toggle" %>
       </div>
    </div>

  <% end %>
</div>

app/views/shared/_nav_reviewer.html.erb
<ul class="nav nav-tabs nav-stacked menu">  
  <li><%= link_to "Accueil", reviewer_root_path %></li>
  <% if current_reviewer_salary.nil? %>
    <li><%= link_to "Se connecter", new_reviewer_salary_session_path %></li>
  <% else %>  
    <li><%= link_to "Modifier le mot de passe", reviewer_password_edit_path %></li>
    <li><%= link_to "Textes", reviewer_texts_url %></li>
    <li><%= link_to "Historiques", stories_reviewer_texts_url %></li>
    <li><%= link_to "Deconnecter", destroy_reviewer_salary_session_path, :method => :delete %></li>
  <% end %>
</ul>