config/routes.rb
AsareoCom::Application.routes.draw do
 
  get "texts/edit"
  resources :texts do
    collection do
      get 'render_fields/:order_id', to: 'texts#render_fields'
      get 'stories', to: 'texts#stories'
      get 'search', to: 'texts#search'
    end
    member do
      get 'quit', to: 'texts#quit'
      post "set_timer", to: "application#set_text_correct_timer"
      post "unlock_text", to: "application#unlock_text"
    end
  end

  resources :projects #do
    devise_for :users, :controllers => {:registrations => "users/registrations"}
    namespace :users do
      get 'password/change', to: "passwords#edit"
      put 'password/update', to: "passwords#update"
  end

  resources :orders,  only: [:index, :show] do
    collection do
      get 'reserved', to:"orders#reserved"
      get 'optional', to:"orders#optional"
      get 'cdc/:cdc_id', to:"orders#show"
    end
    put 'create/:reserver_id', to:"orders#create", as: "create"
    put 'delete/:id_reserve', to:"orders#delete", as: "delete"
  end

  namespace :cp do
    root 'texts#index'

    devise_for :salaries, :controllers => { :registrations => "cp/salaries/registrations", :sessions => "cp/salaries/sessions", :passwords => "cp/salaries/passwords"}

    resources :texts, :only => [:index, :edit, :update] do
      member do
        get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end

    resources :reviewers, :only => [:index, :new, :create, :edit, :update, :destroy]
    get 'reviewers', to: "reviewers#index"

    resource :projects, :only => [:index, :new, :create]
    resources :clients, :only => [:index, :new, :create, :edit, :update] do
      member do
        delete "disable", to: "clients#disable"
        put "enable", to: "clients#enable"
      end
      resources :cdcs, :only => [:index, :new, :create, :edit, :update, :destroy] do
        resources :orders, :only => [:create, :new]
      end 
      resources :orders, :only => [:new]
    end

    resources :orders, :only => [:new, :create, :index, :edit, :update, :destroy, :show] do
      collection do
        get 'stories', to: 'orders#stories'
        get ':id/texts/', to: "orders#showTexts"
      end
    end

    resources :categories_users, :only => [:index, :create]
    resources :levels_users, :only => [:index, :create]

    get "texts/:id/:status", to: "texts#show", as: 'text_show'
    get 'client/:client_id', to:"orders#show"
    get 'cdc/:cdc_id', to:"orders#show"
    get 'orders/new/:id', to: "orders#new", as: 'orderuser'
    get 'levels_users/:id', to: "levels_users#manage",  as: 'level'
    get 'level_user/manage', to: "levels_users#manage",  as: 'managelist'
    get 'password/edit', to: "passwords#edit"
    get 'projects', to: "projects#index" 
    put 'password/update', to: "passwords#update"

  end

  namespace :reviewer do
    root 'texts#index'
    devise_for :salaries, :controllers => { :registrations => "reviewer/salaries/registrations", :sessions => "reviewer/salaries/sessions", :passwords => "reviewer/salaries/passwords", :confirmations => "reviewer/salaries/confirmations"}
    resources :texts, :only => [:index, :edit, :update] do
     member do
       get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end
    

    get 'password/edit', to: "passwords#edit"
    put 'password/update', to: "passwords#update"
    
  end

  namespace :administration do
    devise_for :admins, :controllers => { :sessions => "administration/admins/sessions", :passwords => "administration/admins/passwords"}
    
    resources :texts, :only => [:index, :edit, :update] do
      member do
        get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end

    resources :managers, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :users, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :reviewers, :only => [:index, :new, :create, :edit, :update, :destroy]

    get 'password/edit', to: "passwords#edit"
    put 'password/update', to: "passwords#update"

    resources :projects, :only => [:index, :new, :create, :edit, :update, :destroy]    

    root 'texts#index'
  end

  root 'home#index'

end

app/controllers/administration/orders_controller.rb
class Administration::OrdersController < Administration::AdminsController

  def index
    params[:filtered_attribute] ||= "deadline"
    params[:current_filter] ||= "asc"
    @orders_search = Order.search do
      fulltext params[:q]
      with(:todelete, true)
      order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 10
    end
    @orders = @orders_search.results  
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.texts.collect.count != 0
      redirect_to cp_orders_url, :alert => "Erreur !"
    else
      @order.destroy
      redirect_to administration_orders_url, :notice => "Donnée effacée !"
    end
  end

end

app/controllers/cp/categories_users_controller.rb
class Cp::CategoriesUsersController < Cp::SalariesController

  before_action :set_category, only: [:create]

  def index
    if params[:id]
     @category = Category.find(params[:id])
     @categories = Category.all
     @users = User.all
     render partial: "cp/categories_users/categorie_userList"
    else
     @categories = Category.all
     @users = User.all
    end 
  end

  def create
   @category.user_ids = params[:user_ids]

   if @category.user_ids
      render js: "location.reload();"
      flash[:notice] = "Mise à jour effectuée."
    else
      render js: "location.reload();"
   end
  end

  def destroy
  end

  private

    def set_category
      @category = Category.find(params[:category_id])
    end

end

app/controllers/cp/cdcs_controller.rb
class Cp::CdcsController < Cp::SalariesController
  
  before_action :set_client, only: [:new, :create, :index]

  def index
    @cdcs = Cdc.where(client_id: params[:client_id])
    render partial: "cp/cdcs/index"
  end

  def new  
    @category = Category.all
    @level = Level.all
    @status = Status.where('id IN (1,4)')
    render partial: "cp/cdcs/form"
  end

  def edit
    @cdc =  Cdc.find(params[:id])
    @category = Category.all
    @level = Level.all
    @status = Status.where('id IN (1,4)')
    render partial: "cp/cdcs/edit"
  end

  def create
    cdc_fields = cdc_params.merge({:client_id => @client.id})
    @cdc = Cdc.new cdc_fields
    if @cdc.valid?
      @cdc.save
      flash[:notice] = "Nouveau Cdc ajouté !"
      redirect_to :back
    else
      flash[:alert] = "Les champs avec * sont obligatoires dans la partie CdC !"
      redirect_to :back
    end
  end

  def update
    @cdc = Cdc.find(params[:id])
    if @cdc.update(cdc_params)
       render js: "location.reload();"
       flash[:notice] = "Mise à jour effectuée."
    else
      render js: "alert('Les champs avec * sont obligatoires');"
    end
  end

  def destroy
    @cdc = Cdc.find(params[:id])
    @cdc.destroy
    flash[:notice] = "Donnée effacée"
    render js: "location.reload();"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:client_id])
    end

    def cdc_params      
      params.require(:cdc).permit(:mission, :description, :tarif, :deadline, :category_id, :level_id, :status_id, :file)      
    end

end

app/controllers/cp/clients_controller.rb
class Cp::ClientsController < Cp::SalariesController

	before_action :set_client, only: [:edit, :update, :disable, :enable]
  after_action  :reindex, only: [:create, :update]
  before_action :set_active_menu

	def index
		params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"

    @fetch_clients = Client.search do
      fulltext params[:q]
      if params[:status].blank? ||  params[:status] === "1"
        with(:active, true)
        params[:return] = "1"
      else
        if params[:status] === "2"
        with(:active, false)
        params[:return] = "2"
        else
          if params[:status] === "0"
            params[:return] = "0"
          end
        end
      end
      order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 20
    end
    @clients = @fetch_clients.results
	end

	def new
		@client = Client.new
    @category = Category.all
    @level = Level.all
    @status = Status.where('id IN (1,4)')
    @users = User.where('active = ? AND deleted_at IS NULL', true)
	end

	def create
    # code for client

      $code = ""
    (1..6).each do |n|
      $code += rand(0..9).to_s
    end

		@client = Client.new client_params
    @client.identification = 'CL' + '-' + DateTime.now.strftime("%m%d%Y") + '-' + $code
		if @client.valid?
      @client.user_ids = params[:user_ids]
      cdc = Cdc.new(params[:client][:cdc])
        if cdc.valid? && @client.save
          @client.cdcs << cdc
          redirect_to cp_clients_url, notice: "Nouveau client ajouté."
        else
            @category = Category.all
            @level = Level.all
            @status = Status.where('id IN (1,4)')
            @users = User.where('active = ? AND deleted_at IS NULL', true)
            flash[:alert] = "Veuillez remplir correctement la partie CdC SVP."
            render :action => :new
        end
		else
      @category = Category.all
      @level = Level.all
      @status = Status.where('id IN (1,4)')
      @users = User.where('active = ? AND deleted_at IS NULL', true)
			render :new
		end
	end

  def edit    
    @users = User.where('active = ? AND deleted_at IS NULL', true)
  end

  def update
    if @client.update_attributes client_params
      @client.user_ids = params[:user_ids]
      redirect_to cp_clients_url, notice: "Mise à jour avec succès."
    else
      @users = User.where('active = ? AND deleted_at IS NULL', true)
      render :edit
    end
  end

  def disable
    @client.active = false
    @client.save
    redirect_to cp_clients_url, notice: "Client masqué avec succes."
  end

  def enable
    @client.active = true
    @client.save
    redirect_to cp_clients_url, notice: "Le Client est actif"
  end

  def set_active_menu
    @active_menu = "clients"
  end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params      
      params.require(:client).permit(:name, :address, :phone, :email, :proposal, :billing_date, :billing_date_end, :interlocutor_name, :monthly_volume, :comments, cdcs_attributes: [:mission, :description, :tarif, :deadline, :category_id, :level_id, :status_id, :file])      
    end

    def reindex
      Client.reindex
      Sunspot.commit
    end

end

app/controllers/cp/cp_controller.rb
class Cp::CpController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # override in your ApplicationController or custom Devise::RegistrationsController  

  def after_sign_out_path_for(resource)
    cp_root_url            
  end

  def after_sign_in_path_for(resource)
    cp_root_url    
  end

end

app/controllers/cp/levels_users_controller.rb
class Cp::LevelsUsersController < Cp::SalariesController
  before_action :set_level, only: [:create]

  def index
    params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"
    @fetch_users = User.search do
      order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 10
    end
    if params[:level_id].to_s != ""
      params[:return] = true
      @level = Level.find(params[:level_id])
      @users = @fetch_users.results
    else
      @users = @fetch_users.results
      params[:return] = false
    end
    @levels = Level.all
  end

  def manage
    if params[:id]
     @level = Level.find(params[:id])
     @levels = Level.all
     @users = User.where(:active => true)
     render partial: "cp/levels_users/level_userList"
    else
     @levels = Level.all
     @users = User.all
    end 
  end

  def create
   @level.user_ids = params[:user_ids]

   if @level.user_ids
      render js: "location.reload();"
      flash[:notice] = "Mise à jour effectuée."
    else
      render js: "location.reload();"
   end
  end

  def destroy
  end

  private

    def set_level
      @level = Level.find(params[:level_id])
    end
end

app/controllers/cp/passwords_controller.rb
class Cp::PasswordsController < Cp::SalariesController

  before_filter :authenticate_cp_salary!

  def edit
    @salary = current_cp_salary
  end

  def update
    @salary = current_cp_salary
    # raise params.inspect
    if @salary.update_with_password(params[:salary])
      sign_in(@salary, :bypass => true)
      redirect_to cp_root_path, :notice => "Nouveau mot de passe enregistré !"
    else
      redirect_to cp_password_edit_path, :notice => "Verifier votre mot de passe"
    end
  end

end

app/controllers/cp/projects_controller.rb
class Cp::ProjectsController < Cp::SalariesController
  def index
    params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"

    @fetch_projects = Project.search do
      fulltext params[:q]

      order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 20

    end

    @projects = @fetch_projects.results
  end


  def new
  	@project = Project.new
  end

  def create
  	@project = Project.new(params[:project])

    respond_to do |format|

      if @project.save
        #create project fields
        types = params[:project_field_type] || []
        values = params[:project_field_name] || []
        fields = []
        texts_fields_rendering = ''

        TextField.create(fields)

        format.html { redirect_to cp_texts_url, notice: 'Le projet a bien été crée.' }
        format.json { render action: 'show', status: :created, location: @project }
  	  else	
  	   format.html { render action: 'new' }
    	end

    end

  end

end

app/controllers/cp/reviewers_controller.rb
class Cp::ReviewersController < Cp::SalariesController

	def index
		params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"

		@fetch_reviewers = Salary.search do
			fulltext params[:q]
			with :profil_id, [Profil::CR]

			order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 2

		end

		@reviewers = @fetch_reviewers.results

	end



	def new
		@salary = Salary.new
		respond_to do |format|
			format.html
		end
	end

	def create
		
		@salary = Salary.new params[:salary].merge(:profil_id => Profil::CR)

		respond_to do |format|
	        if @salary.save     
	          format.html { redirect_to cp_reviewers_url, :notice => "Nouveau Correcteur crée" }
      		  #format.html { redirect_to cp_texts_url, notice: 'Correcteur was successfully created.' }
	        else
	          format.html { render action: :new }        
	        end
      	end
	end

	def edit
		@reviewer = Salary.find params[:id]
	end

	def update
		@reviewer = Salary.find params[:id]

		if @reviewer.update_attributes(params[:salary])
			redirect_to cp_reviewers_url, :notice => "Mise à jour effectuée."
		else
			render action: :edit
		end
	end

	def destroy
		@reviewer = Salary.find(params[:id])
		@reviewer.destroy

		redirect_to cp_reviewers_url, :notice => "Donnée effacée"
	end

end 

app/controllers/cp/salaries/confirmations_controller.rb
class Cp::Salaries::ConfirmationsController < Devise::ConfirmationsController
  
end

app/controllers/cp/salaries/passwords_controller.rb
class Cp::Salaries::PasswordsController < Devise::PasswordsController
  
end

app/controllers/cp/salaries/registrations_controller.rb
class Cp::Salaries::RegistrationsController < Devise::RegistrationsController
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
end

app/controllers/cp/salaries/sessions_controller.rb
class Cp::Salaries::SessionsController <  Devise::SessionsController
  
  layout 'cp'
  
end

app/controllers/cp/salaries_controller.rb
class Cp::SalariesController < Cp::CpController
  #before_filter :authenticate_cp_salary!
  before_filter :can_use_cp
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # override in your ApplicationController or custom Devise::RegistrationsController  
  layout 'cp'

  def can_use_cp
    if current_reviewer_salary
      sign_out(current_reviewer_salary)
      redirect_to reviewer_root_url
    else
      authenticate_cp_salary!
    end
  end
  
end

app/helpers/administration/orders_helper.rb
module Administration::OrdersHelper
end

app/helpers/cp/categories_helper.rb
module Cp::CategoriesHelper
end

app/views/cp/orders/_cdcshow.html.erb
<%= form_tag(@cdcs, method: "get", :class=>'form-horizontal') do %>
  <div class="control-group">
    <div class="control-label show_container"><label> Mission : </label>
    <label class="show"><%=@cdc.mission%></label></div>
    <div class="control-label show_container"><label> Categorie : </label>
    <label class="show"><%=@cdc.category.value%></label></div>
    <div class="control-label show_container"><label> Tarif : </label>
    <label class="show"><%=@cdc.tarif%> Ariary</label></div>
    <div class="control-label show_container"><label> Difficulté : </label>
    <label class="show"><%=@cdc.level.value%></label></div>
    <div class="control-label show_container"><label> Date limite : </label>
    <label class="show"><%=@cdc.deadline.strftime("%m/%d/%Y")%></label></div>
    <div class="control-label show_container"><label> statut : </label>
    <label class="show"><%=@cdc.status.value%></label></div>
  </div>

  <div class="control-group">
    <label class="control-label">Description</label>
      <div class="controls">
        <textarea cols="60" rows="12", readonly="true"><%=@cdc.description%></textarea>
      </div>
  </div>

  <div class="control-group"> 
    <div class="controls">  
      <%if @cdc.file? %>
        <div class="border_attached">
        </div>
        <a class="attached_f"  href="<%=@cdc.file.url%>" target="blank" ><%= truncate(@cdc.file_file_name, :length=>15, :separator=>' ')%>
        </a>
      <%end%>
    </div>
  </div>

  <div class="control-group">    
    <div class="controls"> 
      <div onclick="CancelOrder()" class="btn btn-primary lnk-btn">
        Fermer
      </div> 
    </div>    
  </div>

<% end %>

app/views/cp/orders/_orderuserlist.html.erb
<% @users.each do |user| %>
  <%if @level%>
    <% if @level.user_ids.include?(user.id) %>
       <option value="<%= user.id %>">
       <%= user.firstname %>
      </option> 
    <% end %>
  <%end%>             
<% end %>      
   

app/views/cp/orders/_search_form.html.erb
<%= form_tag("/cp/orders", method: "get", :class=>'form-inline stories') do %>
  <%= label_tag(:q, "Rechercher: ") %>
  <%= text_field_tag(:q, params[:q]) %>
  <!--%= select_tag :status_id, options_for_select(@statuses.map{|s| [s.text_status_libelle, s.id]}, params[:status_id]), :prompt => 'Selectionnez un status' %-->
  <%= submit_tag("Rechercher", :class => 'btn btn-primary') %>
<% end %>

app/views/cp/orders/edit.html.erb
<div class="span10">
  <div class="form_revolution span8">
    <h2>Editer commande : <span><%= @order.name%></span></h2>
    <%= form_for [:cp, @order], :html => {:class => "form-horizontal"} do |f| %>
      <div id="friststep">
        <div class="control-group">
          <%= f.label :client, :class => "control-label" %>
          <div class="controls">
            <%= f.select(:client_id, options_for_select(@clients.map{|c| [c.name, c.id]}), :prompt => "Selectionner un client")%>
          </div>
        </div>
        <div id="cdc_list" class="control-group">
          <%= f.label :cdc, :class => "control-label" %>
          <div class="controls">
            <%= f.select(:client_id, options_for_select(@cdcs.map{|c| [c.mission, c.id]}), :prompt => "Selectionner un Cdc")%>
          </div>
        </div>
        <a class="tag_style" onclick="Nextstep('friststep', 'secondstep')">
          Continuer
        </a>
      </div>

        <!-- <div id="Tosecondstep">
          <div class="control-group">
            <%= f.label :text_count, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :text_count, :class => "input-mini" %>
              <a class="tag_style" onclick="create_input_headlines()">Générer champs</a>
            </div>
          </div>
        </div> -->

        <div id="secondstep">
          <div id="headlines_container">
            <%= f.fields_for :headlines do |headline| %>
              <%= headline.text_area :value, class: 'hide'%>
            <%end%>
            <% @headlines.each do |headline|%>
              <div id= "headline<%=@i%>" class="control-group">
                <label class="control-label">Titre <%= @i%></label>
                <div class="controls">
                  <input type="text" name="headlines[]" class="headline_input" value="<%=headline.value%>">
                  <img alt="Deletered" src="/assets/deletered.png" class="this_is_link" onclick="del_headline(<%=@i%>)">
                </div>     
              </div>
              <%@i += 1%>
            <%end%>
          </div>
          <a class="tag_style" onclick="backTo('friststep', 'secondstep', 'Tosecondstep')">
            Revenir à l'étape précédente
          </a>&nbsp
          <a class="tag_style" onclick="add_field()">
            Ajouter un champ
          </a>&nbsp
          <a class="tag_style" onclick="Nextstep('secondstep', 'thirdstep')">
            Continuer
          </a>
        </div>

        <div id="thirdstep">
          <div class="control-group">
            <%= f.label :name, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :name%>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :text_count, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :text_count, :class => "input-mini" %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :word_number, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :word_number, :class => "input-mini" %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :word_price, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :word_price, :class => "input-mini",:placeholder => 'Ariary' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :level, :class => "control-label" %>
            <div class="controls">
              <%= f.select(:level, [['Selectionner', 0],['Simple', 1], ['Intermédiaire', 2], ['Avancé', 3],['Technique ', 4]]) %>
            </div>
          </div>            
          <div class="control-group">
            <%= f.label :deadline, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :deadline %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :date, :class => "control-label" %>
            <div class="controls">
              <%= f.text_field :date %>
            </div>
          </div>
          <a class="tag_style" onclick="backTo('secondstep', 'thirdstep', '')">
            Revenir à l'étape précédente
          </a>&nbsp
          <a class="tag_style" onclick="Nextstep('thirdstep', 'laststep')">
            Continuer
          </a>
        </div>
        <div id="laststep">
          <div class="control-group order">
            <div class="container_select controls">
              <a href='#' id='deselect-all'>deselect all</a>
              <a href='#' id='select-all'>select all</a>
            </div>
            <select id='public-methods' multiple='multiple' name="user_ids[]" class="CatuserList LevuserList">
                  <%@users.each do |userOut|%>
                    <% if @order.cdc.level.user_ids.include?(userOut.id) %>
                      <%@usersIn = @order.users.collect{|u|[u.firstname, u.id] if u.id === userOut.id}.compact%>
                      <% if @usersIn.blank?%>
                        <option value="<%=userOut.id%>">
                            <%=userOut.firstname%>
                        </option>
                      <%else%>
                        <%@usersIn.each do |userIn|%>
                          <option  value="<%=userIn[1]%>" selected ><%=userIn[0]%></option>
                        <%end%>
                      <% end %>
                    <% end %>
                  <%end%>
            </select>         
          </div>
          <div class="control-group">    
            <div class="controls"> 
              <%= link_to "Quitter", cp_orders_path, class: "btn btn-primary lnk-btn"%>
              <% if @order.texts.collect.count == 0%>
                <button class="btn btn-primary lnk-btn" type="submit">Modifier
                </button>
              <%end%>
            </div>
          </div>
          <a class="tag_style" onclick="backTo('thirdstep', 'laststep', '')">
            Revenir à l'étape précédente
          </a>&nbsp
        </div>
    <% end %>
  </div>
</div>

app/views/cp/orders/index.html.erb
<div class="span10">
  <div class="table_adjust">
    <h2 class="text">Mes commandes</h2>
     <div id="partial"></div>
     <%= render :partial => 'search_form' %>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Client</th>
            <th>CdC</th>
            <th><%= render_filter("id", "Nom commande", "cp_orders_path", params) %></th>
            <th>Nombre de textes total</th>
            <th>Nombre textes restant à répartir</th>
            <th>Nombre de textes validés</th>
            <th>Nombre de mots total</th>            
            <th>Tarif au mot (en Ariary)</th>
            <th>Date limite de livraison</th>
            <th>Supprimer</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <%if order.static_text_count > order.text_validated%>
              <tr>
                <td>
                  <div class="this_is_link" onclick="getclient(<%=order.client_id%>)"><%=order.client.name%>
                  </div>
                </td>
                <td>
                  <div class="this_is_link" onclick="getcdcshow(<%=order.cdc_id%>)"><%=order.cdc.mission%>
                  </div>
                </td>
                <td>
                  <% if order.texts.collect.count == 0%>
                    <%= link_to order.name, edit_cp_order_path(order.id), class: "edit_cp_order"%>
                  <%else%>
                    <%=order.name%>
                  <%end%>
                </td>
                <td>
                  <div class="this_is_link" onclick="getTextslist(<%=order.id%>)" href="#partial">
                    <%=order.static_text_count%>
                  </div>
                </td>
                <td>
                  <%=order.text_count%>
                </td>
                <td>
                  <%=order.text_validated%>
                </td>
                <td><%=order.word_number * order.static_text_count%></td>
                <td><%=order.word_price%></td>
                <%if order.deadtime?%>
                  <td>
                    <%=
                    order.deadline.strftime("%d/%m/%Y")+' à '+ Time.strptime(order.deadtime.to_s,"%Y-%m-%d %H:%M:%S %Z").strftime("%H:%M:%S")
                    %>
                  </td>
                <%else%>
                  <td>
                   <%=order.deadline.strftime("%d/%m/%Y")+ ' - Heure non déclarée - '%> 
                  </td>
                <%end%>          
                <td>
                  <% if order.texts.collect.count != 0 %>
                    <%= image_tag("deletered.png", class: "mask")%>
                  <%else%>
                    <%= link_to image_tag("deletered.png"), cp_order_path(order), method: :delete, data: { confirm: 'Etes-vous sur de vouloir continuer?' } %>
                  <% end %>
                </td>
              </tr>
            <%end%>
          <% end %>
        </tbody>
      </table>
  </div>
  <%= will_paginate @orders,:previous_label => '<<', :next_label => '>>' %>
</div>

app/views/cp/orders/new.html.erb
<div class="span10">
  <div class="form_revolution span8">
    <h2>Nouvelle commande</h2>
    <%= render "form" %>
  </div>
</div>