config/routes.rb
AsareoCom::Application.routes.draw do
 
  get "texts/edit"
  resources :texts do
    collection do
      get 'render_fields/:order_id', to: 'texts#render_fields'
      get 'stories', to: 'texts#stories'
      get 'search', to: 'texts#search'
    end
    member do
      get 'quit', to: 'texts#quit'
      post "set_timer", to: "application#set_text_correct_timer"
      post "unlock_text", to: "application#unlock_text"
    end
  end

  resources :projects #do
    devise_for :users, :controllers => {:registrations => "users/registrations"}
    namespace :users do
      get 'password/change', to: "passwords#edit"
      put 'password/update', to: "passwords#update"
  end

  resources :orders,  only: [:index, :show] do
    collection do
      get 'reserved', to:"orders#reserved"
      get 'optional', to:"orders#optional"
      get 'cdc/:cdc_id', to:"orders#show"
    end
    put 'create/:reserver_id', to:"orders#create", as: "create"
    put 'delete/:id_reserve', to:"orders#delete", as: "delete"
  end

  namespace :cp do
    root 'texts#index'

    devise_for :salaries, :controllers => { :registrations => "cp/salaries/registrations", :sessions => "cp/salaries/sessions", :passwords => "cp/salaries/passwords"}

    resources :texts, :only => [:index, :edit, :update] do
      member do
        get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end

    resources :reviewers, :only => [:index, :new, :create, :edit, :update, :destroy]
    get 'reviewers', to: "reviewers#index"

    resource :projects, :only => [:index, :new, :create]
    resources :clients, :only => [:index, :new, :create, :edit, :update] do
      member do
        delete "disable", to: "clients#disable"
        put "enable", to: "clients#enable"
      end
      resources :cdcs, :only => [:index, :new, :create, :edit, :update, :destroy] do
        resources :orders, :only => [:create, :new]
      end 
      resources :orders, :only => [:new]
    end

    resources :orders, :only => [:new, :create, :index, :edit, :update, :destroy, :show] do
      collection do
        get 'stories', to: 'orders#stories'
        get ':id/texts/', to: "orders#showTexts"
      end
    end

    resources :categories_users, :only => [:index, :create]
    resources :levels_users, :only => [:index, :create]

    get "texts/:id/:status", to: "texts#show", as: 'text_show'
    get 'client/:client_id', to:"orders#show"
    get 'cdc/:cdc_id', to:"orders#show"
    get 'orders/new/:id', to: "orders#new", as: 'orderuser'
    get 'levels_users/:id', to: "levels_users#manage",  as: 'level'
    get 'level_user/manage', to: "levels_users#manage",  as: 'managelist'
    get 'password/edit', to: "passwords#edit"
    get 'projects', to: "projects#index" 
    put 'password/update', to: "passwords#update"

  end

  namespace :reviewer do
    root 'texts#index'
    devise_for :salaries, :controllers => { :registrations => "reviewer/salaries/registrations", :sessions => "reviewer/salaries/sessions", :passwords => "reviewer/salaries/passwords", :confirmations => "reviewer/salaries/confirmations"}
    resources :texts, :only => [:index, :edit, :update] do
     member do
       get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end
    

    get 'password/edit', to: "passwords#edit"
    put 'password/update', to: "passwords#update"
    
  end

  namespace :administration do
    devise_for :admins, :controllers => { :sessions => "administration/admins/sessions", :passwords => "administration/admins/passwords"}
    
    resources :texts, :only => [:index, :edit, :update] do
      member do
        get "refuse", to: "texts#refuse"
        get "quit", to: "texts#quit"
      end
      collection do
        get 'stories', to: 'texts#stories'
      end
    end

    resources :managers, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :orders, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :users, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :reviewers, :only => [:index, :new, :create, :edit, :update, :destroy]

    get 'password/edit', to: "passwords#edit"
    put 'password/update', to: "passwords#update"

    resources :projects, :only => [:index, :new, :create, :edit, :update, :destroy]    

    root 'texts#index'
  end

  root 'home#index'

end

app/controllers/administration/admins/confirmations_controller.rb
class Administration::Admins::ConfirmationsController < Devise::ConfirmationsController
  
end

app/controllers/administration/admins/sessions_controller.rb
class Administration::Admins::SessionsController <  Devise::SessionsController
  
  layout 'admin'
  
end

app/controllers/administration/admins_controller.rb
class Administration::AdminsController < ApplicationController
  #before_filter :authenticate_cp_salary!
  before_filter :authenticate_administration_admin!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # override in your ApplicationController or custom Devise::RegistrationsController  
  layout 'admin'
  
end

app/controllers/administration/managers_controller.rb
class Administration::ManagersController < Administration::AdminsController

	after_action :reindex, only: [:create, :update, :destroy]

	def index
		params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"

		@fetch_managers = Salary.search do
			fulltext params[:q]
			with :profil_id, [Profil::CR, Profil::CP]

			order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 2

		end

		@managers = @fetch_managers.results
	end

	def new
		@manager = Salary.new
		respond_to do |format|
			format.html
		end
	end

	def create
		
		@manager = Salary.new params[:salary].merge(:profil_id => Profil::CP)

		respond_to do |format|
	        if @manager.save     
	          format.html { redirect_to administration_managers_url, :notice => "Nouveau Chef de projet crée" }
      		  #format.html { redirect_to cp_texts_url, notice: 'Correcteur was successfully created.' }
	        else
	          format.html { render action: :new }        
	        end
      	end

	end

	def edit
		@manager = Salary.find params[:id]
	end

	def update
		@manager = Salary.find params[:id]

		if @manager.update_attributes(params[:salary])
			redirect_to administration_managers_url, :notice => "Mise à jour effectuée."
		else
			render action: :edit
		end
	end

	def destroy
		@manager = Salary.find(params[:id])
		@manager.destroy

		redirect_to administration_managers_url, :notice => "Donnée effacée"
	end

	private

	def reindex
    Salary.reindex
    Sunspot.commit
  end

end 

app/controllers/administration/orders_controller.rb
class Administration::OrdersController < Administration::AdminsController

  def index
    params[:filtered_attribute] ||= "deadline"
    params[:current_filter] ||= "asc"
    @orders_search = Order.search do
      fulltext params[:q]
      with(:todelete, true)
      order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 10
    end
    @orders = @orders_search.results  
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.texts.collect.count != 0
      redirect_to cp_orders_url, :alert => "Erreur !"
    else
      @order.destroy
      redirect_to administration_orders_url, :notice => "Donnée effacée !"
    end
  end

end

app/controllers/administration/passwords_controller.rb
class Administration::PasswordsController < Administration::AdminsController

  def edit
    @admin = current_administration_admin
  end

  def update
    @admin = current_administration_admin
    # raise params.inspect
    if @admin.update_with_password(params[:admin])
      sign_in(@admin, :bypass => true)
      redirect_to administration_root_path, :notice => "Votre mot de passe a bien été modifié!"
    else
      redirect_to administration_password_edit_path, :notice => "Verifier votre mot de passe"
    end
  end

end

app/controllers/administration/projects_controller.rb
class Administration::ProjectsController < Administration::AdminsController

  def index
  	params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"

    @fetch_projects = Project.search do
      fulltext params[:q]

      order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 20

    end

    @projects = @fetch_projects.results
  end

  def new
  	@project = Project.new
  end

  def create
  	@project = Project.new(params[:project])

    respond_to do |format|

      if @project.save
        #create project fields
        types = params[:project_field_type] || []
        values = params[:project_field_name] || []
        fields = []
        texts_fields_rendering = ''
        types.each_with_index do |v, k|
          
          if v == "varchar"
             texts_fields_rendering = "text_field"
          elsif v == "text"
             texts_fields_rendering = "text_area"
          else 
            texts_fields_rendering = "aaaa"
          end

          fields << {:texts_fields_type => v, :texts_fields_libelle => values[k], :project_id => @project.id, :texts_fields_rendering => texts_fields_rendering}
        end

        TextField.create(fields)

        format.html { redirect_to administration_projects_url, notice: 'Projet crée avec succès.' }
        format.json { render action: 'show', status: :created, location: @project }
  	  else	
  	   format.html { render action: 'new' }
    	end

    end

  end

  def edit
    @project = Project.find params[:id]
  end

  def update
    @project = Project.find params[:id]

    respond_to do |format|
      if @project.update_attributes params[:project]
        format.html { redirect_to administration_projects_url, notice: 'Mise à jour du projet réussie.' }
          format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'edit'}
      end
    end

  end


  def destroy
    @manager = Project.find(params[:id])
    @manager.destroy

    redirect_to administration_managers_url, :notice => "Donnée effacée"
  end

  private

  def reindex
    Project.reindex
    Project.commit
  end

end

app/controllers/administration/reviewers_controller.rb
class Administration::ReviewersController < Administration::AdminsController

	after_action :reindex, only: [:create, :update, :destroy]

	def index
		params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"

		@fetch_reviewers = Salary.search do
			fulltext params[:q]
			with :profil_id, [Profil::CR, Profil::CP]

			order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 2

		end

		@reviewers = @fetch_reviewers.results

	end

	def new
		@reviewer = Salary.new
		respond_to do |format|
			format.html
		end
	end

	def create
		
		@reviewer = Salary.new params[:salary].merge(:profil_id => Profil::CR)

		respond_to do |format|
	        if @reviewer.save     
	          format.html { redirect_to administration_reviewers_url, :notice => "Nouveau Correcteur crée" }
      		  #format.html { redirect_to cp_texts_url, notice: 'Correcteur was successfully created.' }
	        else
	          format.html { render action: :new }        
	        end
      	end

	end

	def edit
		@reviewer = Salary.find params[:id]
	end

	def update
		@reviewer = Salary.find params[:id]

		if @reviewer.update_attributes(params[:salary])
			redirect_to administration_reviewers_url, :notice => "Mise à jour effectuée."
		else
			render action: :edit
		end
	end

	def destroy
		@reviewer = Salary.find(params[:id])
		@reviewer.destroy

		redirect_to administration_reviewers_url, :notice => "Donnée effacée"
	end

	private

	def reindex
    Salary.reindex
    Sunspot.commit
  end

end 

app/controllers/administration/texts_controller.rb
class Administration::TextsController < Administration::AdminsController
  before_action :set_text, only: [:edit, :update, :quit]
  after_action  :reindex, only: [:update]
  def index    
    params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"

    @text_values = TextValue.search do
      fulltext params[:q]
      with :project_id, params[:project_id] if params[:project_id].to_s != ""
      with :status, TextStatus::VALID
      order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 10
    end
    @texts = @text_values.results
    @projects = Project.all
    @statuses = TextStatus.all
    session[:administration_list_back_path] = administration_texts_path
  end

  def edit
    @project = @text.project
    @fields = @project.text_fields
    if @text.can_editable_by? current_administration_admin
        @text.locked_by(current_administration_admin)
    else
      render "read_only"
    end   

  end

  def update   

    unless @text.can_editable_by?(current_administration_admin)
      redirect_to administration_texts_url, notice: 'Ce texte est en cours de correction.Vous ne pouviez plus la modifiée.'
    else

      params[:text_values].each do |k, v|
        @text_value = TextValue.find(k.to_i)
        @text_value.text_value_libelle = v.gsub(/\"/, '\\"');
        @text_value.save
      end 

      #adding text value and text comments
         if !params[:text_comment].blank?
        Comment.create({
          :text_id => @text.id,
          :user_id => current_administration_admin.id,
          :user_class => current_administration_admin.class,
          :name_salary => current_administration_admin.admin_name,
          :text_comment => params[:text_comment]
        })
      end
     # @text.comments << [Comment.new(params)] if !params[:text_comment].blank?
      #@text.text_value = @current_text_value

      #add text correct
      unless @text.corrected?
        @text.corrector_id= current_administration_admin.id
        @text.corrector_class = current_administration_admin.class   
      end     
      #add text validator
      if params[:text][:text_status_id] == TextStatus::ALIVRE        
        @text.validator_id= current_administration_admin.id
        @text.validator_class = current_administration_admin.class
      end   

      respond_to do |format|
        if @text.update(text_params)
          @text.unlocked
          format.html { redirect_to session[:administration_list_back_path], notice: 'Mise à jour du texte réussi.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @text.errors, status: :unprocessable_entity }
        end
      end

    end

  end

  def stories
    params[:filtered_attribute] ||= "updated_at"
    params[:current_filter] ||= "desc"
    @text_values = TextValue.search do
      fulltext params[:q]
      any_of do
        all_of do        
          with :corrector_id, nil
          with :project_id, params[:project_id] if params[:project_id].to_s != ""
          with :status, [1]
        end
        all_of do        
          with :corrector_id, current_administration_admin.id
          with :corrector_class, "Admin"
          with :project_id, params[:project_id] if params[:project_id].to_s != ""
          with :status, [1, 7]
        end  
        all_of do        
          with :corrector_id, nil #current_administration_admin.id 
          with :corrector_class, nil #current_administration_admin.class
          with :project_id, params[:project_id] if params[:project_id].to_s != ""
          with :status, [3, 4]
        end
        all_of do
          with :validator_id, nil #current_administration_admin.id
          with :validator_class, nil #current_administration_admin.class
          with :project_id, params[:project_id] if params[:project_id].to_s != ""
          with :status, [5, 6, 7]
        end
      end
      order_by params[:filtered_attribute].downcase.to_sym, params[:current_filter].downcase.to_sym
      paginate :page => params[:page] || 1, :per_page => 10
    end
    @texts = @text_values.results
    @projects = Project.all
    @statuses = TextStatus.all
    session[:administration_list_back_path] = stories_administration_texts_path
  end

  def quit

      if @text.locked_by?(current_administration_admin)
      @text.unlocked
      redirect_to session[:administration_list_back_path]
    else
      redirect_to session[:administration_list_back_path]
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:texts_num, :user_id, :text_status_id, :project_id)
    end

    def reindex
      TextValue.reindex
      Sunspot.commit
    end

end

app/helpers/administration/orders_helper.rb
module Administration::OrdersHelper
end

app/helpers/cp/projects_helper.rb
module Cp::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/administration/projects/_search_form.html.erb
<%= form_tag("/administration/projects", method: "get", :class=>'form-inline') do %>
  <%= label_tag(:q, "Rechercher:") %>
  <%= text_field_tag(:q, params[:q]) %>
  
  <%= submit_tag("Rechercher", :class => 'btn btn-primary') %>
<% end %>

app/views/administration/projects/edit.html.erb
<div class="offset3 span4 sign"><div class='row-fluid'>

	<div class="span8">
		

		<%= form_for([:administration, @project], :html => {:class => "form-horizontal form_sign_j"}) do |f| %>
		<h2>Creer un projet</h2>
			<% unless @project.errors.empty? %>

				<div class="alert alert-error"><%= @project.errors.full_messages.first %></div> 

			<% end %>
		  <fieldset>
			  <div class="control-group ">
			    <%= f.label :projects_libelle, "Nom", :class => "control-label align_h" %>
			    <div class="controls marge">
			      <%= f.text_field :projects_libelle %>
			      <!--button type="button" class="btn" onclick="add_field()">Ajouter un champ</button-->
			      <button type="submit" class="btn btn-primary">Valider</button>
			    </div>
			     
			  </div>
			  <!--div id="collected_field">
			  	
			  </div-->
			  <div class="control-group">
			    <div class="controls">
			      <!--button type="submit" class="btn btn-primary">Valider</button-->
			    </div>
			  </div>
			</fieldset>

		<% end %>

	</div>

</div>

<div id="field_form" style='display:none'>
	<%= form_tag("#") do %>		
		<div class="alert alert-error" style="display:none;"></div>
	  <%= label_tag(:field_type, "Type") %>
	  <%= select_tag(:field_type, options_for_select([['Champ de caractère', 'varchar'], ['Texte', 'text']]), :prompt => 'Selectionnez un type') %>
	  <%= label_tag(:field_name, "Libellé") %>
	  <%= text_field_tag(:field_name) %>
	  <%= link_to "Ajouter", "#", :class => 'btn btn-primary', :onclick => 'submit_field()' %>
	<% end %>
</div>

<div id="type_textarea" style='display:none;'>
	<div class="control-group">
		<label class="control-label" for="project_field_type[]"></label>
		<div class="controls">
	      <%= select_tag('project_field_type[]', options_for_select([['Champ de caractère', 'varchar'], ['Texte', 'text']]), :id => 'temp') %>
	      <input type='hidden' name='project_field_name[]' id='project_field_name_temp' value="">
	      <a href="#" class="btn btn-danger" onClick="deleteField();">Supprimer</a>
	    </div>
	</div>
</div>
</div>

app/views/administration/projects/index.html.erb
<div class="span10"><h2 class="text">Liste des Projets</h2>
 <%= render :partial => 'search_form' %>
<div class="table_adjust">
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= render_filter("projects_num", "Numéro", "administration_projects_path", params) %></th>
      <th><%= render_filter("projects_libelle", "Nom", "administration_projects_path", params) %></th>      
      <th>Dernière Modification</th>
      <th style="text-align:center;">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.projects_num %></td>
        <td><%= project.projects_libelle %></td>        
        <td><%= project.updated_at %></td>
        <td style="text-align:center;">
          <%= link_to image_tag("edit.png"), edit_administration_project_path(project) %>
          <%= link_to image_tag("deletered.png"), administration_project_path(project), method: :delete, data: { confirm: 'Etes-vous sur de vouloir continuer?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <div id="add_project" class="span2 pull-right">
    <%= link_to "Ajouter", new_administration_project_path, :class => "btn btn-primary" %>
  </div>
<%= will_paginate @projects,:previous_label => '<<', :next_label => '>>'%>
</div>
</div>

app/views/administration/projects/new.html.erb
<div class="sign"><div class="row-fluid">
		<!--h1  class="text"></h1-->
<div>
		<%= form_for([:administration, @project], :html => {:class => "form-horizontal form_sign_j"}) do |f| %>
		<h2>Creer un projet</h2>
		  <% unless @project.errors.empty? %>
				<div class="alert alert-error"><%= @project.errors.full_messages.first %></div> 
			<% end %>
		  <fieldset>
			 <div class="control-group ">
			 	<%= f.label :projects_libelle, "Nom du projet", :class => "control-label align_h" %>
			 	<div class="controls marge">
			 	<%= f.text_field :projects_libelle %>
			 	 
			 	 </div>
			 </div>
			   <div class="control-group">
					    <div class="controls marge">
					 <button type="submit" class="btn btn-primary">Valider</button>
					    </div>
				</div>
			 	</div>
			 </div>

<div class="email"></div>    
			      <!--button type="button" class="btn" onclick="add_field()">Ajouter un champ</button-->
			  <div id="collected_field">
			  	
			  </div>
			  <div class="control-group">
			    <div class="controls">
			      <!--div class="button-send"><span><button type="submit" class="btn btn-primary">Valider</button></span></div-->
			    </div>
			  </div>
			</fieldset>

		<% end %>

<div class="span8">

<div id="field_form" style='display:none'>
	<%= form_tag("#") do %>		
		<div class="alert alert-error" style="display:none;"></div>
	  <%= label_tag(:field_type, "Type") %>
	  <%= select_tag(:field_type, options_for_select([['Champ de caractère', 'varchar'], ['Texte', 'text']]), :prompt => 'Selectionnez un type') %>
	  <%= label_tag(:field_name, "Libellé") %>
	  <%= text_field_tag(:field_name) %>
	  <%= link_to "Ajouter", "#", :class => 'btn btn-primary', :onclick => 'submit_field()' %>
	<% end %>
</div>

<div id="type_textarea" style='display:none;'>
	<div class="control-group">
		<label class="control-label" for="project_field_type[]"></label>
		<div class="controls">
	      <%= select_tag('project_field_type[]', options_for_select([['Champ de caractère', 'varchar'], ['Texte', 'text']]), :id => 'temp') %>
	      <input type='hidden' name='project_field_name[]' id='project_field_name_temp' value="">
	      <a href="#" class="btn btn-danger" onClick="deleteField();">Supprimer</a>
	    </div>
	</div>
</div>
</div>
</div>